/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MmRouteImport } from './routes/mm'
import { Route as IndexRouteImport } from './routes/index'

const MmRoute = MmRouteImport.update({
  id: '/mm',
  path: '/mm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mm': typeof MmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mm': typeof MmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mm': typeof MmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mm'
  id: '__root__' | '/' | '/mm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MmRoute: typeof MmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mm': {
      id: '/mm'
      path: '/mm'
      fullPath: '/mm'
      preLoaderRoute: typeof MmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MmRoute: MmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
